"""Docker generation — produce Dockerfile + docker-compose.yml from analysis."""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dark_factory.setup.project_analyzer import AnalysisResult

_DEP: dict[str, tuple[str, str]] = {
    "Rust": ("RUN cargo fetch", "# cargo test is built-in"),
    "JavaScript": ("RUN npm ci", "RUN npm install -g jest || true"),
    "TypeScript": ("RUN npm ci", "RUN npm install -g jest || true"),
    "Go": ("RUN go mod download", "# go test is built-in"),
    "Python": ("RUN pip install --no-cache-dir -r requirements.txt || true",
               "RUN pip install --no-cache-dir pytest || true"),
    "C#": ("RUN dotnet restore", "# dotnet test is built-in"),
    "Java": ("RUN mvn dependency:resolve -B || true", "# test runner via Maven/Gradle"),
}
_PKGS = "git curl jq ca-certificates"
_HC = '    healthcheck:\n      test: {test}\n      interval: 5s\n      timeout: 3s\n      retries: 10'
_PG_HC = '["CMD-SHELL", "pg_isready -U app"]'
_MY_HC = '["CMD", "mysqladmin", "ping", "-h", "localhost"]'
_RD_HC = '["CMD", "redis-cli", "ping"]'

_T_PG = (
    '  db:\n    image: postgres:16\n    environment:\n'
    '      - POSTGRES_USER=app\n      - POSTGRES_PASSWORD=app\n      - POSTGRES_DB=app\n'
    '    ports:\n      - "127.0.0.1:5432:5432"\n'
    '    volumes:\n      - db-data:/var/lib/postgresql/data\n'
    + _HC.format(test=_PG_HC))
_T_MY = (
    '  mysql:\n    image: mysql:8\n    environment:\n'
    '      - MYSQL_ROOT_PASSWORD=root\n      - MYSQL_DATABASE=app\n'
    '    ports:\n      - "127.0.0.1:3306:3306"\n'
    '    volumes:\n      - mysql-data:/var/lib/mysql\n'
    + _HC.format(test=_MY_HC))
_T_RD = (
    '  redis:\n    image: redis:7-alpine\n'
    '    ports:\n      - "127.0.0.1:6379:6379"\n'
    + _HC.format(test=_RD_HC))
_T_MO = (
    '  mongodb:\n    image: mongo:7\n'
    '    ports:\n      - "127.0.0.1:27017:27017"\n'
    '    volumes:\n      - mongo-data:/data/db')
_TWINS: dict[str, tuple[str, tuple[str, ...]]] = {
    "postgres": (_T_PG, ("db-data",)), "mysql": (_T_MY, ("mysql-data",)),
    "redis": (_T_RD, ()), "mongodb": (_T_MO, ("mongo-data",)),
}
_DB_TWINS = frozenset({"postgres", "mysql", "mongodb"})
_DB_URL: dict[str, str] = {
    "postgres": "postgresql://app:app@db:5432/app",
    "mysql": "mysql://root:root@mysql:3306/app",
    "mongodb": "mongodb://mongodb:27017/app",
}
_DB_SVC = {"postgres": "db", "mysql": "mysql", "mongodb": "mongodb"}


def generate_dockerfile(analysis: AnalysisResult) -> str:
    """Produce a Dockerfile string from analysis results."""
    base = analysis.base_image or "debian:bookworm-slim"
    dep, tdep = _DEP.get(analysis.language, ("", ""))
    lines = [
        "# Auto-generated by Dark Factory -- do not edit manually",
        f"FROM {base}", "",
        "RUN apt-get update && apt-get install -y --no-install-recommends \\",
    ]
    for pkg in _PKGS.split():
        lines.append(f"        {pkg} \\")
    lines.extend(["    && rm -rf /var/lib/apt/lists/*", "",
                   "WORKDIR /workspace", "", "COPY . ."])
    if dep:
        lines.extend(["", dep])
    if tdep:
        lines.extend(["", tdep])
    lines.append("")
    return "\n".join(lines) + "\n"


def _resolve(analysis: AnalysisResult, twins: list[str]) -> list[str]:
    r = list(twins)
    if analysis.has_database and not any(t in r for t in _DB_TWINS):
        r.append("postgres")
    return r


def generate_docker_compose(
    analysis: AnalysisResult, twins: list[str] | None = None,
) -> str:
    """Produce a docker-compose.yml string from analysis and twin services."""
    resolved = _resolve(analysis, twins or [])
    db_twin = next((t for t in resolved if t in _DB_TWINS), "")
    lines = [
        "# Auto-generated by Dark Factory -- do not edit manually", "",
        "services:", "  app:", "    build:", "      context: ../",
        "      dockerfile: .dark-factory/generated/Dockerfile",
        "    volumes:", "      - ../:/workspace", "    working_dir: /workspace",
    ]
    env: list[str] = []
    if db_twin:
        env.append(f"      - DATABASE_URL={_DB_URL[db_twin]}")
    if env:
        lines.append("    environment:")
        lines.extend(env)
    deps: list[str] = []
    if db_twin:
        deps.append(_DB_SVC[db_twin])
    if deps:
        lines.append("    depends_on:")
        for d in deps:
            lines.extend([f"      {d}:", "        condition: service_healthy"])
    if analysis.run_cmd:
        lines.append(f'    command: ["sh", "-c", "{analysis.run_cmd}"]')
    else:
        lines.append('    command: ["tail", "-f", "/dev/null"]')
    vols: list[str] = []
    for twin in resolved:
        tmpl, tv = _TWINS.get(twin, ("", ()))
        if not tmpl:
            continue
        lines.append("")
        lines.append(tmpl)
        vols.extend(tv)
    if vols:
        lines.append("")
        lines.append("volumes:")
        for v in dict.fromkeys(vols):
            lines.append(f"  {v}:")
    lines.append("")
    return "\n".join(lines) + "\n"


def write_generated_files(
    analysis: AnalysisResult, twins: list[str] | None = None,
    *, start: Path | None = None,
) -> tuple[Path, Path]:
    """Write Dockerfile + docker-compose.yml to .dark-factory/generated/."""
    from dark_factory.core.config_manager import resolve_config_dir  # noqa: PLC0415
    out = resolve_config_dir(start) / "generated"
    out.mkdir(parents=True, exist_ok=True)
    df = out / "Dockerfile"
    df.write_text(generate_dockerfile(analysis), encoding="utf-8")
    dc = out / "docker-compose.yml"
    dc.write_text(generate_docker_compose(analysis, twins), encoding="utf-8")
    return df, dc
