"""Test graduation — "a bill becoming a law".

After tests pass both rounds, creates a PR to the crucible repo that adds
the new scenario tests permanently. Tests are renamed (pr-N prefix removed),
checked for conflicts, and committed with full traceability.
"""
from __future__ import annotations

import logging
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from dark_factory.crucible.scenario_gen import ScenarioGenResult, ScenarioTest

logger = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class GraduationResult:
    """Outcome of test graduation."""

    pr_url: str = ""
    pr_number: int = 0
    files_added: tuple[str, ...] = ()
    graduated: bool = False
    error: str = ""


def _rename_for_graduation(file_path: str, pr_number: int) -> str:
    """Convert pr-specific filename to permanent filename.

    ``tests/pr-42-checkout-flow.spec.ts`` -> ``tests/checkout-flow.spec.ts``
    """
    # Use PurePosixPath to keep forward slashes (paths are repo-relative)
    from pathlib import PurePosixPath  # noqa: PLC0415

    p = PurePosixPath(file_path)
    name = p.name
    # Remove pr-N- prefix
    pattern = re.compile(rf"^pr-{pr_number}-", re.I)
    new_name = pattern.sub("", name)
    if new_name == name:
        # Try generic pr-NUMBER- pattern
        new_name = re.sub(r"^pr-\d+-", "", name)
    return str(p.parent / new_name)


def _check_conflicts(crucible_path: Path, graduated_files: list[str]) -> list[str]:
    """Check for naming conflicts with existing tests.

    Returns list of conflicting file paths.
    """
    conflicts: list[str] = []
    for fpath in graduated_files:
        target = crucible_path / fpath
        if target.exists():
            conflicts.append(fpath)
    return conflicts


def _resolve_conflict(file_path: str) -> str:
    """Add -v2 suffix to resolve naming conflict.

    ``tests/checkout-flow.spec.ts`` -> ``tests/checkout-flow-v2.spec.ts``
    """
    from pathlib import PurePosixPath  # noqa: PLC0415

    p = PurePosixPath(file_path)
    # Handle multi-part extensions like .spec.ts
    suffixes = "".join(p.suffixes)
    stem = p.name[: len(p.name) - len(suffixes)]
    return str(p.parent / f"{stem}-v2{suffixes}")


def _generate_pr_body(
    scenario_result: ScenarioGenResult,
    app_repo: str,
    pr_number: int,
) -> str:
    """Generate the PR description for the crucible repo PR."""
    test_count = len(scenario_result.tests)
    fw_used = ", ".join(scenario_result.frameworks_used) or "unknown"

    files_list = "\n".join(
        f"- `{t.file_path}` ({t.framework})"
        for t in scenario_result.tests
    )

    return f"""## Test Graduation from {app_repo} PR #{pr_number}

### Summary
Graduating {test_count} scenario test(s) that passed both Crucible rounds.

### Frameworks
{fw_used}

### PR Diff Summary
{scenario_result.pr_diff_summary}

### Graduated Test Files
{files_list}

### Validation
- Round 1 (Smoke): PASS -- new tests ran successfully
- Round 2 (Regression): PASS -- all existing tests + new tests passed

---
*Auto-generated by Dark Factory Crucible*
"""


# ── Public API ──────────────────────────────────────────────────


def graduate_tests(
    crucible_path: str | Path,
    scenario_result: ScenarioGenResult,
    app_repo: str,
    pr_number: int,
    *,
    git_fn: Any = None,
    gh_fn: Any = None,
) -> GraduationResult:
    """Create a PR to the crucible repo adding graduated tests.

    Steps:
    1. Create branch: ``crucible/graduate-pr-{N}``
    2. Rename test files (remove ``pr-N-`` prefix)
    3. Check for naming conflicts (resolve with ``-v2`` suffix)
    4. Commit with descriptive message
    5. Push and create PR

    Args:
        crucible_path: Path to local crucible repo clone.
        scenario_result: Results from scenario generation.
        app_repo: Source app repo (owner/repo).
        pr_number: App PR number being graduated.
        git_fn: Optional git command callable (for testing).
        gh_fn: Optional gh CLI callable (for testing).
    """
    cruc = Path(crucible_path)

    if not scenario_result or not scenario_result.tests:
        return GraduationResult(error="No tests to graduate")

    # Import shell helpers
    if git_fn is None:
        from dark_factory.integrations.shell import git as _git  # noqa: PLC0415
        git_fn = _git
    if gh_fn is None:
        from dark_factory.integrations.shell import gh as _gh  # noqa: PLC0415
        gh_fn = _gh

    cwd = str(cruc)
    branch = f"crucible/graduate-pr-{pr_number}"
    timestamp = int(time.time())

    # 1. Create branch
    git_fn(["checkout", "-b", f"{branch}-{timestamp}"], cwd=cwd)

    # 2. Rename and move files
    graduated_files: list[str] = []
    for test in scenario_result.tests:
        src = cruc / test.file_path
        if not src.exists():
            logger.warning("Test file not found: %s", src)
            continue

        new_path = _rename_for_graduation(test.file_path, pr_number)

        # 3. Check for conflicts
        if (cruc / new_path).exists():
            new_path = _resolve_conflict(new_path)
            logger.info("Resolved conflict: %s -> %s", test.file_path, new_path)

        target = cruc / new_path
        target.parent.mkdir(parents=True, exist_ok=True)

        if str(src) != str(target):
            try:
                content = src.read_text(encoding="utf-8")
                target.write_text(content, encoding="utf-8")
                src.unlink()
            except OSError as exc:
                logger.error("Failed to rename %s: %s", src, exc)
                continue

        graduated_files.append(new_path)

    if not graduated_files:
        return GraduationResult(error="No test files could be graduated")

    # 4. Stage and commit
    git_fn(["add", "-A"], cwd=cwd)
    commit_msg = (
        f"feat(crucible): graduate tests from {app_repo} PR #{pr_number}\n\n"
        f"Graduated {len(graduated_files)} test file(s) that passed "
        f"both Crucible rounds (smoke + regression).\n\n"
        f"Files: {', '.join(graduated_files)}"
    )
    r = git_fn(["commit", "-m", commit_msg], cwd=cwd)
    if hasattr(r, "returncode") and r.returncode != 0:
        return GraduationResult(
            files_added=tuple(graduated_files),
            error=f"Commit failed: {getattr(r, 'stderr', '')}",
        )

    # 5. Push
    actual_branch = f"{branch}-{timestamp}"
    r = git_fn(["push", "-u", "origin", actual_branch], cwd=cwd)
    if hasattr(r, "returncode") and r.returncode != 0:
        return GraduationResult(
            files_added=tuple(graduated_files),
            error=f"Push failed: {getattr(r, 'stderr', '')}",
        )

    # 6. Create PR
    pr_title = f"feat(crucible): graduate tests from PR #{pr_number}"
    pr_body = _generate_pr_body(scenario_result, app_repo, pr_number)
    r = gh_fn(
        ["pr", "create",
         "--title", pr_title,
         "--body", pr_body,
         "--head", actual_branch,
         "--base", "main"],
        cwd=cwd,
    )
    pr_url = ""
    pr_num = 0
    if hasattr(r, "returncode") and r.returncode == 0:
        pr_url = getattr(r, "stdout", "").strip()
        # Extract PR number from URL
        m = re.search(r"/pull/(\d+)", pr_url)
        if m:
            pr_num = int(m.group(1))

    logger.info(
        "Graduated %d tests from %s PR #%d -> %s",
        len(graduated_files), app_repo, pr_number, pr_url or "PR creation failed",
    )

    return GraduationResult(
        pr_url=pr_url,
        pr_number=pr_num,
        files_added=tuple(graduated_files),
        graduated=bool(pr_url),
        error="" if pr_url else f"PR creation returned: {getattr(r, 'stderr', '')}",
    )
